/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.directory.api:api-all:2.0.0.AM3")
    compileOnly("org.projectlombok:lombok:1.18.8")
    annotationProcessor("org.projectlombok:lombok:1.18.8")
    implementation("com.fasterxml.jackson.core:jackson-core:2.9.9")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.9.9")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.9.9")
    implementation("org.apache.logging.log4j:log4j-api:2.7")
    implementation("org.apache.logging.log4j:log4j-core:2.7")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.7")
}

group = "io.github.univerage.ualberta-harvester"
version = "1.0-SNAPSHOT"
description = "ualberta-harvester"
java.sourceCompatibility = JavaVersion.VERSION_1_8

tasks.withType<Jar>() {
    manifest {
        attributes["Main-Class"] = "io.github.univerage.ualbertaharvester.Main"
    }

    from(configurations.compileClasspath.map { config -> config.map { if (it.isDirectory) it else zipTree(it) } })
}